# Generated by Django 4.2.7 on 2026-05-24 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lesson_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(default=10)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(default=dict, help_text='Mapping of question_id to selected answer')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('option_a', models.CharField(max_length=300, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=300, verbose_name='Option B')),
                ('option_c', models.CharField(max_length=300, verbose_name='Option C')),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Explication détaillée de la bonne réponse')),
                ('level', models.CharField(choices=[('remember', 'Se souvenir'), ('understand', 'Comprendre'), ('apply', 'Appliquer'), ('analyze', 'Analyser'), ('evaluate', 'Évaluer')], default='remember', max_length=20)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='main.lesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
    ]
