# Generated by Django 4.2.7 on 2026-06-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_video_file_alter_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, help_text="Collez l'URL YouTube (ex: https://www.youtube.com/watch?v=...)"),
        ),
    ]
